[project]
name = "pluto-analytics"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.2",
    "getdaft>=0.4.15",
    "httpx>=0.28.1",
    "marimo>=0.13.11",
    "polars>=1.29.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]

[tool.marimo.runtime]
dotenv = [".env"]
