version: 2
updates:
  # Check for python dependencies in analytics package
  - package-ecosystem: "pip"
    directory: "/packages/analytics"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: auto

  # Check for npm dependencies in web package
  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: auto

  # Check for npm dependencies in cms package
  - package-ecosystem: "npm"
    directory: "/packages/cms"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: auto

  # Check for updates to Docker in web package
  - package-ecosystem: "docker"
    directory: "/packages/web"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Check for updates to Docker in cms package
  - package-ecosystem: "docker"
    directory: "/packages/cms"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
