version: '3.9'

volumes:
  pluto-db-data:
  pluto-db-admin-data:

networks:
  db-cms:
  db-admin-db:
  cms-survey-admin:
  survey-admin-survey-public:

services:
  # Postgres 15
  db:
    build: ./services/db
    env_file: ./services/db/.env
    container_name: pluto-db
    restart: always
    volumes:
      - pluto-db-data:/var/lib/postgresql/data
    networks:
      db-cms:
      db-admin-db:

  # PgAdmin 4
  db-admin:
    build: ./services/db-admin
    env_file: ./services/db-admin/.env
    container_name: pluto-db-admin
    restart: always
    ports:
      - '9000:80'
    depends_on:
      - db
    volumes:
      - pluto-db-admin-data:/var/lib/pgadmin
    networks:
      db-cms:
      db-admin-db:

  # Strapi v4
  cms:
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile
    env_file: ./apps/cms/.env.production
    restart: always
    depends_on:
      - db
    ports:
      - '9001:1337'
    networks:
      db-cms:
      cms-survey-admin:

  # Next.js 13.4
  survey-admin:
    build:
      context: .
      dockerfile: ./apps/survey-admin/Dockerfile
    env_file:
      - ./apps/survey-admin/.env.production
      - ./apps/survey-admin/.env.local.docker
    restart: always
    depends_on:
      - cms
    ports:
      - '9002:3000'
    networks:
      cms-survey-admin:
      survey-admin-survey-public:

  # Vue 2.7
  survey-public:
    build:
      context: .
      dockerfile: ./apps/survey-public/Dockerfile
    env_file:
      - ./apps/survey-public/.env.production
      - ./apps/survey-public/.env.local
    restart: always
    depends_on:
      - survey-admin
    ports:
      - '9003:8080'
    networks:
      # Connection to the admin backend for the rebuild CRON job
      survey-admin-survey-public:
