[tool.poetry]
name = "survey-tools"
version = "0.1.0"
description = ""
authors = ["Péter Ferenc Gyarmati <dev.petergy@gmail.com>"]
readme = "README.md"
packages = [{include = "pluto_survey_tools"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
