name: Push Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Create `config_key` file from secret
        run: echo "${{ secrets.SECRET_CONFIG_KEY }}" > config_key

      - name: Decrypt all repository secret files
        run: bash ./scripts/secrets.sh --decrypt

      - name: Create `commit-hash.txt`
        run: echo $GITHUB_SHA > commit-hash.txt

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          REPOSITORY_NAME=pluto
          REPOSITORY_TAG=nx-base
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY_NAME:$REPOSITORY_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY_NAME:$REPOSITORY_TAG

      - name: Log out from Docker Hub
        run: docker logout
