name: Build and Push Web Docker Image

on:
  push:
    paths:
      - ".github/workflows/web-docker-build.yml"
      - "packages/web/**"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/web

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.local file
        run: |
          mkdir -p packages/web
          cat > packages/web/.env.local << EOF
          STRAPI_WEBHOOK_SECRET=${{ secrets.STRAPI_WEBHOOK_SECRET }}
          NEXT_PUBLIC_STRAPI_BASE_URL=${{ secrets.NEXT_PUBLIC_STRAPI_BASE_URL }}
          STRAPI_API_BASE_URL=${{ secrets.STRAPI_API_BASE_URL }}
          STRAPI_API_TOKEN=${{ secrets.STRAPI_API_TOKEN }}
          NEXT_PUBLIC_UMAMI_SCRIPT_URL=${{ secrets.NEXT_PUBLIC_UMAMI_SCRIPT_URL }}
          NEXT_PUBLIC_UMAMI_WEBSITE_ID=${{ secrets.NEXT_PUBLIC_UMAMI_WEBSITE_ID }}
          NEXT_PUBLIC_HEYFORM_FORM_ID=${{ secrets.NEXT_PUBLIC_HEYFORM_FORM_ID }}
          NEXT_PUBLIC_HEYFORM_CUSTOM_URL=${{ secrets.NEXT_PUBLIC_HEYFORM_CUSTOM_URL }}
          NEXT_PUBLIC_HEYFORM_SCRIPT_URL=${{ secrets.NEXT_PUBLIC_HEYFORM_SCRIPT_URL }}
          NEXT_PUBLIC_CLARITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_CLARITY_PROJECT_ID }}
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch,prefix=preview-
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/web/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-files: |
            "env_file=./packages/web/.env.local"
